### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [weijia-cheng/dorothy-day_the-eleventh-virgin#1]
- ~Re. ignoring the CSS lint error, I would replace `<em class="underlined'>` with `<strong>` which you can target directly and more accurately describes what's going on (strong emphasis).~ :heavy_check_mark: 
- ~Re. the other ignored error, proper names like song names do not get italics even if they are in non-English.~ :heavy_check_mark: 
- ~Remove quotes from Bible books: ‘Acts.’, others?~ :heavy_check_mark: this is the only instance
- ~In the food table, use `<th>` for the header cells and not `<td>`~ :heavy_check_mark: 
- ~In the CSS, instead of `:not()` for the tables, use `:first-of-type` since that will be simplified by the build process. Likewise target `th` or `td` instead of `:not(colspan)`~ :heavy_check_mark: 
- ~Long description typo: `Day‛s`~ :heavy_check_mark:

**Comment by acabal** [comment]
~Also, in all endnotes change the cite to `<abbr class="initialism">S.E.</abbr> Editor` to clarify that the notes are from us and not some previous editor~ :heavy_check_mark:

**Comment by acabal** [comment]
~Dedication is missing required styling from the manual~ :heavy_check_mark:

**Comment by weijia-cheng** [comment]
Thanks for the review @acabal -- fixed all the comments and sending this back to you.
